### ISSUE TITLE
Game file injection?

### ISSUE THREAD

**Issue by losh11** [techiew/EldenRingModLoader#1]
I'm wondering if you're working on the ability to add the ability to inject modified game files into Elden Ring outside of the archive. For e.g. to load in a modified texture mapping file, which maps the Dualsense icons to Xbox. 
I created the PS5/PS4 icons mod, and would be happy to work with you on getting something like this working. In the future this could be used to add ultrawide game assets etc.

**Comment by techiew** [comment]
I've been thinking about it and how to do it and it should be possible, although somewhat complex. It's low priority on my to-do list though. First I gotta polish the smaller mods I've released and then I was thinking about creating a regulation.bin merger so more mods replacing that could be used at once.

The regulation.bin merger would involve injecting files into memory, or hooking the game in some way or other. Could be a nice stepping stone to creating a more generic file injector.

**Comment by Arthursza** [comment]
if you just mean the controller icons, i swear i saw something in special K that claims that feature

**Comment by techiew** [comment]
Mod engine 2 has this functionality, therefore I won't be looking at it.
