### ISSUE TITLE
Linux compatibility 

### ISSUE THREAD

**Issue by Golodir** [techiew/EldenRingModLoader#3]
Hi there, I have been trying to get this to work with wine (via lutris)

The mods are not loaded when eldenringmodloader is installed into the folder (no mod_loader_log.txt is created, game launches without issue --> see [lutris-log](https://pastebin.com/4Vys90aE)), changing the wine dll-overrides to native,buildin for dinput8 seems to load the mods (see [mod_loader_log](https://pastebin.com/9fUmAcCG))

However with dll-override Elden Ring crashes shortly after boot with an "invalid signature" window popping up and closing on itself.
The [lutris-log](https://pastebin.com/aJ1xf914) outputs:
`4980: Unhandled exception: unimplemented function DINPUT8.dll.DirectInput8Create called in 64-bit code (0x00000001700338c0).`

**Comment by rahenry** [comment]
I would also be interested in linux compatibility

**Comment by leberknecht** [comment]
Wondering: i disabled EAC via er-patcher ( https://github.com/gurrgur/er-patcher ) but the mod still seems not to load. Is there any other way to get it running on proton?

**Comment by IvarWithoutBones** [comment]
I was running into the problem of the mods just not being picked up at all as well, but I was able to fix it with the following steps:

* I've marked `dinput8.dll` as executable with `chmod +x dinput8.dll`
* I've added the following to my launch options: `WINEDLLOVERRIDES="dinput8.dll=n,b" %command%`

This also works perfectly together with `er-patcher`, for that my launch commmand is as follows: `/home/ivv/working/er-patcher/bin/er-patcher --all -- env WINEDLLOVERRIDES="dinput8.dll=n,b" %command%`

At least the `DisableRuneLoss` mod now works perfectly, although I haven't tested any others. Really appreciate that this is working now, thanks to everyone who worked on linux support :blush:

**Comment by leberknecht** [comment]
Interesting, if i do that, im getting a little dialog box that says "Could not find signature!" when i start the game

**Comment by Golodir** [comment]
this should be fixed with https://github.com/techiew/EldenRingMods/pull/9
